version: '3.8'

services:

  frontend:
    container_name: frontend
    build: Frontend
    env_file:
      - Frontend/.env
    ports:
      - '3000:3000'

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: on-failure
    expose:
      - '6379'
    volumes:
      - redis_data:/data

  celery-worker:
    container_name: celery-worker
    build: Background
    env_file:
      - Background/.env
    depends_on:
      - redis

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile  # it is built from the file as we need to install extra extension
    restart: on-failure
    env_file:
      - .env
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: api
    build: API
    env_file:
      - API/.env
    ports:
      - '5000:5000'
    depends_on:
      - postgres

volumes:
  redis_data:
  postgres_data:
